### ISSUE TITLE
Program crashes on CNT generation for tubes with length != 3 and radius != 1

### ISSUE THREAD

**Issue by tab10** [ajkerr0/kappa#105]
File "/Users/tim/Documents/PycharmProjects/kappa/kappa/molecule.py", line 732, in _combine
    if index1 in mol1.faces[face1].closed:
UnboundLocalError: local variable 'face1' referenced before assignment

**Comment by ajkerr0** [comment]
Closing this issue because I believe we figured out the problem with that script were the indices of the interfacial atoms only being true for CNTs of that dimension.
