### ISSUE TITLE
More code required for GROMACS compatibility

### ISSUE THREAD

**Issue by tab10** [ajkerr0/kappa#22]
.pdb functionality is installed for certain molecules. Works using molecule.posList, molecule.zList, molecule.bondList. However more code is required to directly interact with gromacs and generate more files. Specifically .top files, containing position data and all interactions and strengths. Should this be part of this package? A config file and SLURM script will also be needed for the supercomputer.

**Comment by ajkerr0** [comment]
Yes, sounds like a good idea to put in the package.  We could have a GROMACS sub-directory/package that holds the relevant codes.

I would think GROMACS has a way to input 'standard' forcefield interactions such as bond length, bond angles, torsionals, etc?  If we can figure out the correspondance we might be able to incorporate that info in the forcefield classes.  The molecule objects have the forcefields and force parameters as attributes, so I'm thinking it must be possible to build these .top files from the same molcule objects as the pdb's.  You're going to have to take point on this issue or point me in the right direction in terms of learning what exactly you need.

**Comment by tab10** [comment]
Yeah I can probably figure it out, ok I will make it part of the package.

**Comment by ajkerr0** [comment]
You don't have to do this in isolation, we can have a conversation this week about it?

**Comment by tab10** [comment]
Yeah let's talk tomorrow. I found some bugs in the code, but I'll fix them today. You can install VMD and try loading a generated .pdb. I think you'll be surprised what all you can do for visualization now.

**Comment by ajkerr0** [comment]
I took a good look at the GROMACS manual last night.  We should just be able to use their default Amber forcefield(s).  We hope that our molecular enhancements can be reflected by any of their forcefields if they are physical...we can also input our own forcefield file if we really needed to?

Just realized the .top files you talked about contained the molecular topology information.  It should be really easy to pull bonding information (bonds, angles, dihedrals) from my Molecule objects and put them in a text file in the right format.

**Comment by ajkerr0** [comment]
Leaving these links for self-reference:
http://www.gromacs.org/Documentation/How-tos/Carbon_Nanotube
http://chembytes.wikidot.com/grocnt

**Comment by ajkerr0** [comment]
For Alex:
- Generate '.itp' '.rtp' and 'n2t' files

For Tim:
- Make .top and .gro files from Alex's file generation

**Comment by ajkerr0** [comment]
Closing this issue.  Effectively moving it to a Project where we can tackle these required features separately.
