### ISSUE TITLE
Functionality for .pdb export and import

### ISSUE THREAD

**Issue by ajkerr0** [ajkerr0/kappa#3]
Need input from @tab10.

Need a way to export kappa's molecules for use in other codes, namely GROMACS.

It would also be nice if we had an easy way to carry molecule objects around.

**Comment by tab10** [comment]
It'd be helpful to create an examples folder with how to generate some molecule like graphene, maybe write the steps in a txt file?

**Comment by ajkerr0** [comment]
Yes, it would be nice to have a tutorial up at some point.  I can send you something I showed Dr. Mullen and Dr. Glatzhofer before.

**Comment by ajkerr0** [comment]
Maybe this is pedantic but since we haven't actually merged the files yet I don't want to close this issue at this time.  Should it be closed when we merge into `master` or into some other branch?  I honestly don't know the best practices.
